### ISSUE TITLE
[AUDIT] SOG SMS Notifications page

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-docs#804]
Audit this page: https://docs.reactioncommerce.com/docs/sms-notifications

This means running through all instructions on the page, updating any out of date screenshots, correcting any incorrect documentation, and removing any out-of-date documentation.

As SMS notifications are not used anymore, this page can probably be removed, but please read through first to confirm.

**Comment by chrispotter** [comment]
This seems to be a limitation of the Docusaurus framework. 

This feature has been deprecated and the SMS page has been deleted, along with all references to the feature in the "master" code branch! 

However, the documentation still shows this as a feature 2.0.0 because of the fallback structure of the documentation engine.

Should I go back through all the versioned sidebars and docs and remove these SMS features? Techinically they still available if you download an old version of RC (i think the versioned docs have it in 1.14??)

@kieckhafer @aldeed What do y'all think?

**Comment by chrispotter** [comment]
Since we are focusing on doc diff with the fallback structure, perhaps we should be updating the docs to have "This feature has been deprecated in version X.X.X" rather than deleting the file?

**Comment by chrispotter** [comment]
however...it seems that the SMS NOtifications was accidentally left in the sidebar for version-2.0.0. So it's probably worth discussing that, if you can't find the docs except by explicit url is it worth the deprecation message?

**Comment by chrispotter** [comment]
<img width="1592" alt="Screen Shot 2019-06-25 at 11 17 43 AM" src="https://user-images.githubusercontent.com/7069752/60110892-e527d100-973a-11e9-9f73-5dc0ee38372d.png">
Seems that this answers that....If you hvae a page without a sidebar item, it will break the page. Maybe the answer is how we've done this so far and delete completely.....

**Comment by machikoyasuda** [comment]
For posterity, the SMS plugin was moved out to here: https://github.com/reaction-contrib/meteor-notifications-sms People can still install it but it's not part of stock Reaction.
