### ISSUE TITLE
Deprecate Design System

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/reaction-docs#966]
**Describe the documentation you'd like to read:**

I'd like to see a note at the top of every page on the component library design system documentation indicating the documentation may be or is out of date. Special attention should be paid to how theming is done as the following document does not seem current nor a good idea in Storefront as it conflicts with MUI theming guidance.

https://designsystem.reactioncommerce.com/#!/Theming%20Components

**Comment by janus-reith** [comment]
Hi @balibebas, while I agree that the component library should probably be deprecate as at least in my personal experience it created more issues than it solved, I'd like to make sure we're on the same page with theming here:

The component library is mainly using `styled-components`, not `material-ui`.
(MUI is only used in two components, `QuantityInput` and `StripePaymentCheckoutAction`.)

The docs are correct so far, stating that in order to visually customize the component library, you would need to wrap things in a styled-components `ThemeProvider` - **Not to be confused with the same name `ThemeProvider` from Material-UI.**
The pattern with the `rui_` prefix is correct aswell.

In the storefront, you can wrap `_app.js` with both the SC and MUI `ThemeProviders` and they should not conflict (At least in theory, practically the two libs can conflict, but unrelated to the use of these ThemeProviders ).
The MUI would contain styling for the components in the storefront, the SC one for the component library (+ other SC components you might have in the storefront).
This means you would certainly end up duplicating some style definitions for both systems, and for the upcoming Material-UI 5, there have been considerations regarding that, so you can either use emotion or sc and the architecture is pluggable.
